# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Valebat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Valebat
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'

  target 'ValebatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ValebatUITests' do
    # Pods for testing
  end

end
